apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudio-frontend
  namespace: cloudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudio-frontend
  template:
    metadata:
      labels:
        app: cloudio-frontend
    spec:
      containers:
      - name: frontend
        image: 102586998566.dkr.ecr.eu-west-1.amazonaws.com/cloudio-frontend:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-registry-helper
---
apiVersion: v1
kind: Service
metadata:
  name: cloudio-frontend-service
  namespace: cloudio
spec:
  type: NodePort
  selector:
    app: cloudio-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080